In [11]:
import tensorflow as tf

In [12]:
#a=tf.constant([1,2,3])
#b=tf.constant([4,5,6])
tf.constant([4,5,6])

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/home/yongcanpan/anaconda3/envs/pytorch/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-7e1fa1899874>", line 3, in <module>
    tf.constant([4,5,6])
AttributeError: module 'tensorflow' has no attribute 'constant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yongcanpan/anaconda3/envs/pytorch/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2034, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AttributeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yongcanpan/anaconda3/envs/pytorch/lib/python3.6/site-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(e

AttributeError: module 'tensorflow' has no attribute 'constant'

In [6]:
#tensorflow中，乘法运算。包含点乘*/tf.multiply，
#矩阵乘tf.matmul
print(a*b)
print(tf.multiply(a,b))


ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/home/yongcanpan/anaconda3/envs/pytorch/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-ace4c05da8f1>", line 3, in <module>
    print(a*b)
NameError: name 'a' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yongcanpan/anaconda3/envs/pytorch/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2034, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NameError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yongcanpan/anaconda3/envs/pytorch/lib/python3.6/site-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  

NameError: name 'a' is not defined

In [40]:
#矩阵乘法运算
c = tf.expand_dims(a,0)
print(c)
d=tf.expand_dims(b,1)
print(d)
print(tf.matmul(c,d))

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[4]
 [5]
 [6]], shape=(3, 1), dtype=int32)
tf.Tensor([[32]], shape=(1, 1), dtype=int32)


In [88]:
#tf.transpose(input,transpose_a,transpose_b),transpose_b==True，默认将最后两个维度转秩
a=tf.constant([[[1,2,3],[4,5,6]]])
b=tf.constant([[[1,1,1],[2,2,2]]])
c=tf.matmul(a,b,transpose_b=True)
print(c.shape)

(1, 2, 2)


In [46]:
#tf.one_hot操作，a表示原转换元素的位置，即indices（应用比如转换word——id）；4表示深度，即转换后的维度depth
a=[2,3,0]
print(tf.one_hot(a,4))

tf.Tensor(
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [58]:
#tf.slice(input,begin,size)：从input中抽取begin维度之后的元素，新抽取的元素维度为size
#例子一，x[0][1]=2开始，打印shape=[2,1]的元素。
x=[[1,2,3],[4,5,6]]  
begin = [0,1] 
size = [2,1] 
tf.slice(x,begin,size)

<tf.Tensor: id=150, shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]], dtype=int32)>

In [60]:
#例子二，x[0][1]=2开始，打印shape=[2,2]的元素。
x=[[1,2,3],[4,5,6]]  
begin = [0,1] 
size = [2,2] 
tf.slice(x,begin,size)

<tf.Tensor: id=158, shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [62]:
#例子三，x[0][1]=2开始，打印shape=[2,-1]的元素。shape=[2,-1]表示2行，尽可能多的列。
x=[[1,2,3],[4,5,6]]  
begin = [0,1] 
size = [2,2] 
tf.slice(x,begin,size)

<tf.Tensor: id=166, shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [64]:
#例子四，x[0][0]=1开始，打印shape=[2,1]的元素。
x=[[1,2,3],[4,5,6]]  
begin = [0,0] 
size = [1,2] 
tf.slice(x,begin,size)

<tf.Tensor: id=174, shape=(1, 2), dtype=int32, numpy=array([[1, 2]], dtype=int32)>

In [69]:
# tf.shape 的相关操作
x=tf.constant([[1,2],[3,4]])
b=x.shape
print(type(b))
# shape.as_list对shape变成list。
c=b.as_list()
print(c)

<class 'tensorflow.python.framework.tensor_shape.TensorShape'>
[2, 2]


In [72]:
#tf.cast Tensor类型转换
x = tf.constant([1.8, 2.2], dtype=tf.float32)
tf.dtypes.cast(x, tf.int32)  # [1, 2], dtype=tf.int32

<tf.Tensor: id=183, shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [89]:
# tf.transpose默认维度完全颠倒
a= tf.constant([[[1,2,3],[4,5,6]]])
print(a.shape)
#默认输出，维度完全颠倒
b=tf.transpose(a)
print(b.shape)
#将第二维和第三维转秩
c=tf.transpose(a,[0,2,1])
print(c.shape)

(1, 2, 3)
(3, 2, 1)
(1, 3, 2)


In [94]:
# tf.gather(params,indices)根据索引从参数轴上收集切片,params要选取的值，indices要选取的位置。
#在-1轴上选取2，0，1的为位置
a=tf.gather([0,1,2,3],[2,0,1],axis=-1)
print(a)

tf.Tensor([2 0 1], shape=(3,), dtype=int32)


In [98]:
#tf.reshape 改变维度，把第二维度改为第三个维度
tf.reshape([[1,2,3],[4,5,6]],[2,1,3])

<tf.Tensor: id=248, shape=(2, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]]], dtype=int32)>

In [1]:
# tf.control_dependencies
help(tf.control_dependencies)

NameError: name 'tf' is not defined

In [5]:
#tf.range
#range()函数用于创建数字序列变量，有以下两种形式：

#range(limit, delta=1, dtype=None, name='range')
#range(start, limit, delta=1, dtype=None, name='range')
#该数字序列开始于 start 并且将以 delta 为增量扩展到不包括 limit 时的最大值结束，类似python的range函数。

#dtype 为类型转换，即如果输入的数据为整数，就不要写dtype=tf.int32,否则会抛出异常。
print(tf.range(1,5))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
